# Generated by Django 3.0.3 on 2020-02-12 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='grupos',
            new_name='groups',
        ),
    ]
